version: "3"

services:
  nginx-personal-website:
    image: nginx:alpine
    platform: linux/amd64
    container_name: nginx-personal-website
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx/prod.nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/nginx/cert/:/etc/ssl/:ro
      - ./dist:/var/www/vite-app

  minio:
    image: quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z-cpuv1
    platform: linux/amd64
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file: .env
    volumes:
      - ~/minio_data:/data
    command: server /data --console-address ":9001"

  nginx-minio:
    image: nginx:alpine
    platform: linux/amd64
    container_name: nginx-personal-website
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx/prod.storage.nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf/nginx/cert/:/etc/ssl/:ro
    depends_on:
      - minio
