version: "3"

services:
  geni-personal-website:
    build: .
    image: gn/personal-website
    platform: linux/amd64
    container_name: geni-personal-website
    # environment:
    #   - NODE_ENV=production
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    ports:
      - "3000:3000"
    # command: npm start
