version: "3"

services:
  nginx-personal-website:
    image: nginx:alpine
    platform: linux/amd64
    container_name: nginx-personal-website
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/dev.nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist:/var/www/vite-app

  minio:
    image: quay.io/minio/minio
    platform: linux/amd64
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file: .env
    command: server /data --console-address ":9001"
