// This file is auto-generated by @hey-api/openapi-ts

export type BlogPost = {
  title: string;
  slug: string;
  content: string;
  id: string;
};

export type BlogPostData = {
  title: string;
  slug: string;
  content: string;
};

export type Body_login_access_token_login_access_token_post = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type Token = {
  access_token: string;
  token_type?: string;
};

export type User = {
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  full_name?: string;
  id: string;
  hashed_password: string;
};

export type UserCreate = {
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  full_name?: string;
  password: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type GetAllBlogPostsBlogGetResponse = Array<BlogPost>;

export type CreateBlogPostBlogPostData = {
  requestBody: BlogPostData;
};

export type CreateBlogPostBlogPostResponse = BlogPost;

export type GetBlogPostByIdBlogBlogIdGetData = {
  blogId: string;
};

export type GetBlogPostByIdBlogBlogIdGetResponse = BlogPost;

export type UpdateBlogPostBlogBlogIdPutData = {
  blogId: string;
  requestBody: BlogPostData;
};

export type UpdateBlogPostBlogBlogIdPutResponse = BlogPost;

export type DeleteBlogPostBlogBlogIdDeleteData = {
  blogId: string;
};

export type DeleteBlogPostBlogBlogIdDeleteResponse = unknown;

export type HealthCheckHealthGetResponse = unknown;

export type LoginAccessTokenLoginAccessTokenPostData = {
  formData: Body_login_access_token_login_access_token_post;
};

export type LoginAccessTokenLoginAccessTokenPostResponse = Token;

export type ReadUsersMeUsersMeGetResponse = User;

export type GetUsersUsersGetResponse = Array<User>;

export type GetUserUsersUserIdGetData = {
  userId: string;
};

export type GetUserUsersUserIdGetResponse = User;

export type DeleteUserUsersUserIdDeleteData = {
  userId: string;
};

export type DeleteUserUsersUserIdDeleteResponse = unknown;

export type RegisterUserUsersRegisterPostData = {
  requestBody: UserCreate;
};

export type RegisterUserUsersRegisterPostResponse = User;

export type UpdateUserRoleUsersUserIdRolePatchData = {
  isSuperuser: boolean;
  userId: string;
};

export type UpdateUserRoleUsersUserIdRolePatchResponse = unknown;
