// This file is auto-generated by @hey-api/openapi-ts

export type BlogPost = {
  id?: string;
  title: string;
  slug: string;
  content: string;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type GetAllBlogPostsBlogGetResponse = Array<BlogPost>;

export type CreateBlogPostBlogPostData = {
  requestBody: BlogPost;
};

export type CreateBlogPostBlogPostResponse = BlogPost;

export type GetBlogPostByIdBlogBlogIdGetData = {
  blogId: string;
};

export type GetBlogPostByIdBlogBlogIdGetResponse = BlogPost;

export type UpdateBlogPostBlogBlogIdPutData = {
  blogId: string;
  requestBody: BlogPost;
};

export type UpdateBlogPostBlogBlogIdPutResponse = BlogPost;

export type DeleteBlogPostBlogBlogIdDeleteData = {
  blogId: string;
};

export type DeleteBlogPostBlogBlogIdDeleteResponse = unknown;

export type HealthCheckHealthGetResponse = unknown;
